<a href="https://colab.research.google.com/github/haechis/ML_trial/blob/main/ML_trial_03_3_%ED%8A%B9%EC%84%B1_%EA%B3%B5%ED%95%99%EA%B3%BC_%EA%B7%9C%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 특성 공학과 규제

- 선형 회귀

선형 회귀는 특성이 많을수록 엄청난 효과를 냅니다.

- 다중 회귀

선형 회귀를 사용할 때는 하나의 특성을 사용하였습니다.
하나의 특성을 사용했을 때 선형 회귀 모델이 학습하는 것은 '직선'입니다.

다중 회귀는 여러 개의 특성을 사용한 선형 회귀입니다.

2개의 특성을 사용했을 때 선형 회귀 모델이 학습하는 것은 '평면'입니다.

y = a * x1 + b * x2 + c 

(where, y: 타깃, x1: 특성1, x2: 특성2, c: 절편)

특성이 많은 고차원에서는 선형 회귀가 매우 복잡한 모델을 표현할 수 있습니다.

- 특성 공학 (feature engineerign)

농어 예제의 경우 길이와 높이와 같은 특성 외에 '농어의 길이 x 농어의 높이'를 새로운 특성으로 만드는 것을 특성 공학이라고 합니다.

# 데이터 준비

- 판다스

데이터 분석 라이브러리입니다. 데이터프레임(dataframe)은 판다스의 핵심 데이터 구조입니다.  

csv 파일을 손쉽게 배열로 변환할 수 있습니다. 

In [1]:
import pandas as pd # pd는 관례적인 판다스의 별칭입니다.
df = pd.read_csv('https://bit.ly/perch_csv_data')
perch_full = df.to_numpy()
print(perch_full)
# 농어의
# c1(길이), c2(높이), c3(두께)

[[ 8.4   2.11  1.41]
 [13.7   3.53  2.  ]
 [15.    3.82  2.43]
 [16.2   4.59  2.63]
 [17.4   4.59  2.94]
 [18.    5.22  3.32]
 [18.7   5.2   3.12]
 [19.    5.64  3.05]
 [19.6   5.14  3.04]
 [20.    5.08  2.77]
 [21.    5.69  3.56]
 [21.    5.92  3.31]
 [21.    5.69  3.67]
 [21.3   6.38  3.53]
 [22.    6.11  3.41]
 [22.    5.64  3.52]
 [22.    6.11  3.52]
 [22.    5.88  3.52]
 [22.    5.52  4.  ]
 [22.5   5.86  3.62]
 [22.5   6.79  3.62]
 [22.7   5.95  3.63]
 [23.    5.22  3.63]
 [23.5   6.28  3.72]
 [24.    7.29  3.72]
 [24.    6.38  3.82]
 [24.6   6.73  4.17]
 [25.    6.44  3.68]
 [25.6   6.56  4.24]
 [26.5   7.17  4.14]
 [27.3   8.32  5.14]
 [27.5   7.17  4.34]
 [27.5   7.05  4.34]
 [27.5   7.28  4.57]
 [28.    7.82  4.2 ]
 [28.7   7.59  4.64]
 [30.    7.62  4.77]
 [32.8  10.03  6.02]
 [34.5  10.26  6.39]
 [35.   11.49  7.8 ]
 [36.5  10.88  6.86]
 [36.   10.61  6.74]
 [37.   10.84  6.26]
 [37.   10.57  6.37]
 [39.   11.14  7.49]
 [39.   11.14  6.  ]
 [39.   12.43  7.35]
 [40.   11.93

In [3]:
# 타깃 데이터
import numpy as np
perch_length = np.array([8.4, 13.7, 15.0, 16.2, 17.4, 18.0, 18.7, 19.0, 19.6, 20.0, 21.0,
       21.0, 21.0, 21.3, 22.0, 22.0, 22.0, 22.0, 22.0, 22.5, 22.5, 22.7,
       23.0, 23.5, 24.0, 24.0, 24.6, 25.0, 25.6, 26.5, 27.3, 27.5, 27.5,
       27.5, 28.0, 28.7, 30.0, 32.8, 34.5, 35.0, 36.5, 36.0, 37.0, 37.0,
       39.0, 39.0, 39.0, 40.0, 40.0, 40.0, 40.0, 42.0, 43.0, 43.0, 43.5,
       44.0])
perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])

In [4]:
# perch_full과 perch_weight를 훈련 세트와 테스트 세트로 나눕니다.
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(perch_full, perch_weight, random_state = 42)

- 사이킷런의 변환기

변환기(transformer): 사이킷런은 특성을 만들거나 전처리하기 위한 다양한 클래스 제공합니다. 

여러 변환기 중에서 sklearn.preprocessing 패키지의 PolynomialFeatures 클래스를 사용하겠습니다.

In [5]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures()
## poly.fit
# 2와 3의 특성공학을 이용하여 만들 수 있는 조합을 구합니다.
poly.fit([[2,3]])
# 1(기본), 2, 3, 4(2x2), 6(2x3), 9(3x3)
print(poly.transform([[2,3]]))

[[1. 2. 3. 4. 6. 9.]]


In [6]:
# poly.fit에서 절편을 의미하는 1(기본)을 제외하려면 아래와 같은 방법을 사용하면 됩니다.
poly = PolynomialFeatures(include_bias = False)
poly.fit([[2,3]])
print(poly.transform([[2,3]]))

[[2. 3. 4. 6. 9.]]


In [7]:
## 위에서 알아본 내용을 이용하여 train_input을 변환한 데이터를 train_poly에 저장하고 배열의 크기를 확인하겠습니다.
poly = PolynomialFeatures(include_bias = False)
poly.fit(train_input)
train_poly = poly.transform(train_input)
print(train_poly.shape)

(42, 9)


In [8]:
# 9개의 특성이 어떻게 만들어졌는지 확인해 보겠습니다.
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x0^2', 'x0 x1', 'x0 x2', 'x1^2', 'x1 x2',
       'x2^2'], dtype=object)

In [10]:
# 테스트 세트도 동일하게 변환하겠습니다.
test_poly = poly.transform(test_input)
# !! 훈련 세트를 기준으로 테스트 세트를 변환!!